# Generated by Django 3.2.3 on 2023-12-16 18:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useruser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useruser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='useruser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=256, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='useruser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой электронной почтой уже существует.'}, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='useruser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterUniqueTogether(
            name='useruser',
            unique_together=set(),
        ),
    ]
